### ISSUE TITLE
packages not found

### ISSUE THREAD

**Issue by rpatel1303** [BlackArbsCEO/iex_intraday_equity_downloader_public#1]
Hello,
I tried to create environment using environment.yml but i am constantly having issues with package not found (arrow-cpp=0.9.0=py36_7). Any suggestions?

**Comment by BlackArbsCEO** [comment]
Unfortunately conda has issues installing from `yaml` files in general. You might try to delete that particular package from the `yaml` file and try to install it after creating and activating your environment using either `conda` or `pip`.
